### ISSUE TITLE
Possible to add a toggle to highlight suspect bots names above them?

### ISSUE THREAD

**Issue by zeakzz** [Ferrariic/bot-detector#11]
i think thatd be pretty cool

**Comment by extreme4all** [comment]
This is one of the ideas we discussed, we might implement something like this. Thanks for the feature requestOn 26 Mar 2021 21:12, zeakzz ***@***.***> wrote:
i think thatd be pretty cool

**Comment by Ferrariic** [comment]
Yes, our dev team can discuss that! Thank you :)
