### ISSUE TITLE
data source

### ISSUE THREAD

**Issue by extreme4all** [Ferrariic/bot-detector#6]
hey, can i help making the flask api & NN?

**Comment by Ferrariic** [comment]
Sure! Just submit post requests and I'll accept them if they're able to help contribute to the system! let me update the repo before you do that - I'll let you know once that's done!

**Comment by extreme4all** [comment]
great, yeah access to the data on your server and a format must be agreed upon

**Comment by Ferrariic** [comment]
https://github.com/Ferrariic/Python-Bot-Detector

Here you go, these are all the files I think you would need. It includes everything that's being worked on atm.

**Comment by extreme4all** [comment]
probably most work is spend on feature engineering :)

**Comment by extreme4all** [comment]
like if we have a flow to label banned users, aka users that we found on the highscores but later we cannot find them on the highscores (or i believe banned users are banned from the highscores)

**Comment by Ferrariic** [comment]
Yeah that would be a great addition! What do you think about sampling users within a group, and then having automated weekly checks on those users to see if they still appear on the hiscores? We might be able to use that to evaluate ban rate - as one idea.
