### ISSUE TITLE
Notification configurability

### ISSUE THREAD

**Issue by nathanmobbs** [Ferrariic/bot-detector#9]
The `Bot Detector: N Player Names Uploaded Successfully!` message triggers notifications in RuneLite.

This clashes with users that rely on the Idle Notifier plugin to play afk.

Please can we keep the ability to contribute automatically, but remove the in-game chat message and notification. It would be nice if it's configurable if we want to see the number for some reason. It should really default to `off`

**Comment by ThorntonMatthewD** [comment]
Hello! Once this [pull request](https://github.com/runelite/plugin-hub/pull/1201) is merged into the RuneLite Plugin Hub's master branch there will be an option to disable notifications. Hopefully it'll be live soon!

![Screenshot from 2021-03-19 13-50-55](https://user-images.githubusercontent.com/44626690/111822491-3934fa80-88ba-11eb-874e-8c3d0bebeef7.png)

**Comment by ThorntonMatthewD** [comment]
86e4e60ff22fa06f11ec6b25dd642f679de67be5 Is the commit with the fix.
